name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: 
"614388036286.dkr.ecr.us-east-1.amazonaws.com/deja-demo-app:latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_URI .
          echo "Pushing Docker image..."
          docker push $IMAGE_URI

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: deja-demo-app
          cluster: deja-demo-app-cluster
          image: $IMAGE_URI
          wait-for-service-stability: true

